### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop-provider-elasticsearch#10]
Have you tested the native app support for android and iphone?

I am getting this error when I try and bring in to an android phone

the legend comes in fine, just no data

index > TypeError: Cannot read property 'wkid' of undefined                                                  │
│[12] index     Mem:  71 MB    CPU:  0 %  onli ││ index >     at buildESQuery (es/provider/models/esmodel.js:113:37)   │
│[13] index     Mem:  84 MB    CPU:  0 %  onli ││ index >     at indexInfo.getMapping.then.mapping (es/provider/model  │
│[14] index     Mem:  88 MB    CPU:  0 %  onli ││ s/esmodel.js:36:31)                                                                                          │
│[15] index     Mem:  70 MB    CPU:  0 %  onli ││ index >     at process._tickDomainCallback (internal/process/next_tick.js:135:7)                             │
│[16] index     Mem:  82 MB    CPU:  0 %  onli ││ index > You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:       │
│[17] index     Mem:  82 MB    CPU:  0 %  onli ││ index > TypeError: Cannot read property 'wkid' of undefined                                                  │
│[18] index     Mem:  71 MB    CPU:  0 %  onli ││ index >     at buildESQuery (/home/ec2-/es/provider/models/esmodel.js:113:37)   │
│[19] index     Mem:  70 MB    CPU:  0 %  onli ││ index >     at indexInfo.getMapping.then.mapping (/es/provider/model  │
│                                              ││ s/esmodel.js:36:31)                                                                                          │
│                                              ││ index >     at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by dhatcher** [comment]
I have not.  Looks like the mobile version doesn't send a spatial reference with its bounding box.

**Comment by dhatcher** [comment]
Is this still a problem?  If so could you provide a sample of what is being passed to the provider?
