### ISSUE TITLE
looks like this provider is not working with the latest Koop release

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop-provider-elasticsearch#12]
I just upgraded my koop instance and it wont work with this provider, any thoughts?

(node:5648) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): SyntaxError: Unexpected token o in JSON at position 1

**Comment by rgwozdz** [comment]
The latest upgrade to koop-core includes parsing of query/body parameters that arrive as JSON strings, so it might have something to do with that.  Perhaps you are trying to JSON parse a query param that has already been parsed by koop-core?

**Comment by dhatcher** [comment]
Closing, if this is still an issue let me know.
