### ISSUE TITLE
Exciting stuff.

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop-provider-elasticsearch#17]
All, thanks for posting this updated es provider, we are just now digging in.  I have a couple clarifications.

What is the param in the config file called "shapeIndices" it looks like it has something to do with the join index?

With regard to aggregations I notice that there is two options, one is geohash, one is geohex, when I look in the code I notice a reference to an aggServerConfig

const options = {
            hostname: aggServerConfig.hostname,
            port: aggServerConfig.port,
            path: '/algorithm/execute',
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            }
        };

I am wondering in what is that in reference to?

**Comment by dhatcher** [comment]
@keithfraley yes the shapeIndices section is for joining an index with no shapes to a separate index that does have geometry of some sort.  There is more information in the readme about how those work along with an example configuration.

The geohex aggregation is non-functional currently and that portion of code will probably be pulled out.  It was really just left in there as an example in case anyone wanted to implement their own aggregation.

**Comment by keithfraley** [comment]
Thanks, we are excited to jump in and plan on contributing as much as we can :)

**Comment by rgwozdz** [comment]
Can this be closed?

**Comment by zakhtar1998** [comment]
@keithfraley looks like you have managed to get koop working, is is possible if you could share your email address as i would like to contact you. I am currently encountering some issue in retrieving geo_point data, so would love to reach out to you for some help.
