### ISSUE TITLE
Proper URL?

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop-provider-elasticsearch#2]
I was thinking the :host variable was the name of the cluster and the :id was the name of my index (http://myurl.com/es/mycluster/myindex/FeatureService/0), but when I plug those in I get back "cannot get ..."

Any thoughts?

**Found it**

http://myurl.com/koop/es/mycluster/myindex/FeatureService/0

**Comment by keithfraley** [comment]
the only way I could get this to work was to name the host, ID and the index the name of the index is ES.

**Comment by dhatcher** [comment]
They shouldn't all have to be the same.  I'll add some documentation in the readme on how that's created.

**Comment by dhatcher** [comment]
Updated Readme with more info on this.
