### ISSUE TITLE
Lacking documentation

### ISSUE THREAD

**Issue by KennethOveln** [koopjs/koop-provider-elasticsearch#33]
I have issues getting things to work since there is missing lots of documentation.
Or is it a requirement that i should read and understand all code to make it work?

Whats the ES support? Versions? All should work?

Parameters like:
timeInfo parameters - (start,end, intervall..) important for timeEnabled layers
timefields have to be in unix_ms to get the time extent correct.

Aggregations parameters - ["geohash"] doesn't work at all, cant even see layer/1 anymore since 2.5. Works fine in Kibana. 
How should custom aggregations be specified?

Custom symbolizer...

the list goes on...

**Comment by rgwozdz** [comment]
This is a free, open source code repository.  It relies on people volunteering their time and effort.  You're welcome to use it, ignore it, contribute to it.  The rant above is unlikely to inspire anyone to volunteer more time to address your concerns.

**Comment by KennethOveln** [comment]
I wasn't trying to be offensive in my post.
I really like this project and only want to able to use and understand it better.

But its kinda useless if nothing is working and if functions isn't properly documented. 
Whats good about new features if i don't know how to use them?

Its not a big effort to add a line or 2 in the documentation how to configure something.
I would gladly do it if i could.

Most likely ppl would like to contribute more if they understood it.

**Comment by rgwozdz** [comment]
We would be more than willing to review any contribution you would like to make.

**Comment by dhatcher** [comment]
@KennethOveln it really comes down to someone having time to help update the documentation. There is a bug fix coming soon with an update to the readme that shows the new way to specify aggregations.  Instead of strings they are now objects:
`{"name": "geohash"}`
