### ISSUE TITLE
Table not displaying records when timestamp is part of index

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop-provider-elasticsearch#4]
I am not able to see the results in the table.

I have narrowed it down to this error

{
error: "Cannot read property 'timestamp' of undefined"
}

If returnGeometry=true then the features come across and draw on the map.
if returnGeometry=false the you get the error message uptop.

**Comment by keithfraley** [comment]
this is still an issue, it appears that the datetime field in the table has the first letter capitalized by default, not sure if that might be an issue?

**Comment by dhatcher** [comment]
Can you share the return fields and date fields in your configuration?  Or at least the part with this field?

**Comment by keithfraley** [comment]
I was able to get  data into the table by adding the following to the fields 

      "indices": [
        {
          "index": "test",
          "maxResults": 6000,
          "geometryField": "geometry",
          "geometryType": "geo_point",
          "returnFields": [
            "UWI", "COMMON_NAME", "WELL_NAME", "SPATIALIZED_DATE"
          ],
          "dateFields": [
            "**properties.**SPATIALIZED_DATE"
          ]

**Comment by keithfraley** [comment]
that actually did not fix the issue, I am not sure what exactly the reason is for not loading into the table. It seems like it has to do with the time field, but not exactly sure.  Does the table load for you?  I dont know if it matters but my fields are all lower case...

**Comment by dhatcher** [comment]
Date fields work fine and show up in the table on everything we've tried, including all lowercase.  Do they look right in the pop-ups?  Could you post the field definition in elastic?

**Comment by keithfraley** [comment]
{
  "mappings": {
    "sm": {
      "properties": {
        "geometry": {
          "type": "geo_point"
        },
        "fieldone": {
          "type": "long",
          "ignore_malformed": true
        },
        "eventtime": {
          "type": "date"
        },
        "lon": {
          "type": "float",
          "ignore_malformed": true
        },
        "lat": {
          "type": "float",
          "ignore_malformed": true
        },
        "fieldtwo": {
          "type": "float",
          "ignore_malformed": true
        },
        "fieldthree": {
          "type": "float",
          "ignore_malformed": true
        },
        "fieldfour": {
          "type": "long",
          "ignore_malformed": true
        },
        "fieldfive": {
          "type": "long",
          "ignore_malformed": true
        },
        "fieldsix": {
          "type": "long",
          "ignore_malformed": true
        },
        "fieldseven": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "fieldeight": {
          "type": "long",
          "ignore_malformed": true
        },
        "fieldnine": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "fieldten": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "type": {
          "type": "long"
        },
        "fieldeleven": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "fieldtwelve": {
          "type": "long"
        },
        "fieldthirteen": {
          "type": "long"
        },
        "fieldfourteen": {
          "type": "long"
        },
        "fieldfifteen": {
          "type": "long"
        },
        "fieldsixteen": {
          "type": "long"
        },
        "fieldseventeen": {
          "type": "long"
        },
        "fieldeighteen": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "fieldnineteen": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "fieldtwenty": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        }
      }
    }
  }
}

**Comment by dhatcher** [comment]
Your dates are declared as date type with no format specified. This means that by default ES uses strict_date_optional_time||epoch_millis which is fairly forgiving. The provider gives parsing the date a shot and then falls back on what the mapping has listed as the format if it has trouble. I'm guessing your date values might be in a format the provider is having trouble parsing and since no explicit format is given it fails. Could you share a sample date or are they in different formats?

**Comment by keithfraley** [comment]
"eventtime": 1523487910000, 

this is what comes back when I query

**Comment by keithfraley** [comment]
Update. when I explicitly set the format to milliseconds in the mapping I get the following error

Trace: couldn't parse date: 1523630275000
    at indexConfig.dateFields.forEach.error (/home/ec2-user/environment/OutputEngine/es/provider/utils/hitConverter.js:88:37)
    at Array.forEach (native)
    at HitConverter.featureFromHit (/home/ec2-user/environment/OutputEngine/es/provider/utils/hitConverter.js:71:36)
    at /home/ec2-user/environment/OutputEngine/es/provider/models/esmodel.js:42:52
    at process._tickCallback (internal/process/next_tick.js:109:7)


"eventtime": {
	"type": "date",
	"format": "epoch_millis"
}

**Comment by dhatcher** [comment]
This happens because momentjs (what we use to parse dates) doesn't understand the epoch_millis format.  It should have worked just fine before you added the format though.  Milliseconds should work just fine.  I can't see a reason you should be having any issues.

I'll change the parsing logic to handle your current case more gracefully but I don't think that's the issue with your dates now working.

**Comment by keithfraley** [comment]
its not in the hitconverter, is it?

**Comment by dhatcher** [comment]
What ended up being the fix for this?

**Comment by keithfraley** [comment]
returnGeometry=false and still setting outputCRS was blowing up the
returning json

**Comment by rgwozdz** [comment]
@dhatcher - I released an update to FeatureServer that removes `outSR` from requests that also have `returnGeometry=false`
