### ISSUE TITLE
Is it possible to pass a user/password authentification with the provider ?

### ISSUE THREAD

**Issue by FoicikRemi** [koopjs/koop-provider-elasticsearch#46]
Hello everyone ! 

I'm Remi from France, I'm working for the city of Versailles and I'm highly interested by this provider.

My main problematic is :
We have several smart cities components connected to an elastic search database, we wanted to connect to index in this database without making replication in order to visualize datas with a map server in webmap, dashboard etc.... I understood that it could be possible with koop and this provider, am I right ? 

I have actually some difficulties with using this provider. My first question is : Is it possible to connect to es with a user/password authentification ? I couldn't find an example with this issue and I tried naively to add a password variable in the esConnection class inside the default.json file..... 

I'm really sorry in advance that I can't contribute with the coding part but I can maybe use some time in order to write some more "user friendly", detailed documentation if you're interested.

Best regard, 

Rémi

**Comment by qQsss777** [comment]
Hi Remi, 
looking at the code it looks like this feature is implemented : https://github.com/koopjs/koop-provider-elasticsearch/blob/master/src/utils/elasticConnectUtil.js#L31. 

So try ( i didn't try) to add username and password keys to your esNameForServiceURLs object in your config file. For example:

```
{
  "esConnections": {
    "esNameForServiceURLs": {
      "id": "esNameForServiceURLs",
      "username": "mysusername",
      "password": "mypassword",
      "protocol": "http://",
      "port": 9200,
      "hosts": [
        "localhost"
      ],
      "shapeIndices": {
        "states": {
          "geometryField": "geometry",
          "geometryType": "Polygon",
          "joinField": "NAME"
        }
      },
...
}
```

**Comment by FoicikRemi** [comment]
Hi Mark, 

Thanks for your response. I saw this file but I wanted to be sure it was fully implemented.

I generated my app, I added Es provider 

![image](https://user-images.githubusercontent.com/19668261/151147597-429c50e6-ddbb-4a8f-a87e-aaab63e33b13.png)

Here's the configuration of the es provider in "C:\Users\remi.foicik\testitoune\node_modules\@koopjs\provider-elasticsearch\config\default.json"

![image](https://user-images.githubusercontent.com/19668261/151148189-5602d4e2-de1f-4245-9bf4-05c19f11932f.png)

Then I can start the app with koop server or nmp start commands, 

![image](https://user-images.githubusercontent.com/19668261/151148336-0916c3f6-6711-4bf1-9027-d5a45d419a2e.png)

![image](https://user-images.githubusercontent.com/19668261/151148377-a323647c-d4a2-42f5-b703-792e5e8956ae.png)

But now, I have no idea how to construct the output URL ..... 

For example, in the Github provider, I could follow this 
![image](https://user-images.githubusercontent.com/19668261/151150453-04d0d2b7-dfc9-41cd-81a2-8359eb97d304.png)

I really don't know where is the problem, the app itself, the es config file, the es connexion itself.

Does anyone have a functional app I can use as example ? With output URL. It can really help me resolving my issues.

Best regards, 

Rémi

**Comment by qQsss777** [comment]
Can you modify versailles key with that :

```
"versailles":{
      "id": "versailles",
      "protocol": "http://",
      "port": 9200,
      "hosts": [
        "172.28.4.240"
      ],
      ... other keys/values
}

```

**Comment by FoicikRemi** [comment]
I also tried this way, the main problem is I don't understand what is the Output URL in order to test.

**Comment by qQsss777** [comment]
did you try http://localhost:8080/es/172.28.4.420/versailles/FeatureServer' ?

**Comment by zakhtar1998** [comment]
MY ES index does not have a FQDN, and therefore.i need to provide the username and password, how can i do so? I tried the following:
{
  "esConnections": {
    "esNameForServiceURLs": {
      "id": "esNameForServiceURLs",
      "userName": "mysusername",
      "password": "mypassword",
      "protocol": "http://",
      "port": 9200,
      "hosts": [
        "localhost"
      ],
...

But this returned an error when starting koop. Does anyone know how we can authernticate ES?

**Comment by zakhtar1998** [comment]
@FoicikRemi the url in your case would be http://localhost:8080/es/rest/services/versailles/winext/FeatureServer. Give this a try and let me knwo if you can retrieve the geo_point json.
