### ISSUE TITLE
Issue accessing es apis

### ISSUE THREAD

**Issue by zakhtar1998** [koopjs/koop-provider-elasticsearch#48]
Hello,

I have an elasticsearch index which does not require a username or password(http://10.4.2.41:9500/hurricane_dorian_2019_test) and I have koop installed where i have set the relevant config and proxy routes. When i run the koop server it is working fine, and when i access the /es/res/info it is showing fine. However, when i access /es/rest/services/10.4.2.41/local/FeatureServer it gives a proxy error (even though i have the route specified). Can anyone let me know what the problem is here and how I can resolve this?

**Koop running**
<img width="739" alt="image" src="https://user-images.githubusercontent.com/103567436/163144850-e71b233b-3d93-4f95-80ff-2c8436637c03.png">

**Config File**
<img width="438" alt="image" src="https://user-images.githubusercontent.com/103567436/163237939-d6cf1a06-ef74-479f-96f4-0d30f1669bcc.png">

Sample JSON (trying to retrieve lat and lon from location_info --> resolved_location)
<img width="427" alt="image" src="https://user-images.githubusercontent.com/103567436/163237414-03d9de0d-031e-414e-9773-a4865b109de1.png">

**Info showing fine**
![image](https://user-images.githubusercontent.com/103567436/163145036-6fc69db2-dfe6-4aae-be72-8991f1918e6a.png)

**Proxy Error on Webpage**
![image](https://user-images.githubusercontent.com/103567436/163145333-184c656e-1e10-49e1-8ce2-30208d5f8be5.png)

**Koop Error**
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/103567436/163145451-77e3fba2-c840-4498-9f58-2e0d32f44c60.png">

**Mod Proxy File**
<img width="643" alt="image" src="https://user-images.githubusercontent.com/103567436/163145717-34ea413f-c3e1-4ecc-b096-94249af4e1ab.png">

**Comment by rgwozdz** [comment]
Looks to me like the EsClient fails to initialize because of an invalid connection string.  I assume it is invalid because the userName and password is `undefined`.  If you put a break point in elasticConnectUtil.js you might confirm that.

How common is it that an Elastic instance doesn't require and username / password?  That seem strange to me.  Wouldn't that mean anybody could connect and do bad things like delete or edit documents?

**Comment by zakhtar1998** [comment]
So in order to be connected to the ES Index I have to be in the organization network for which we don't need a username and password. Please see the screenshot below showing the ES connecting successfully without any credentials when I use my VPM to connect to the organization. Without the VPN, the ES will not connect.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/103567436/163451671-6d7b742b-52ea-4080-b828-d2ea32296d1f.png">

Does that mean I have to make the ES public with the FQDN for this error to be resolved?

**Comment by atangeman** [comment]
To my knowledge, the ES cluster is internal to their their network and is not accessible outside via NAT or proxy.

**Comment by rgwozdz** [comment]
See https://github.com/koopjs/koop-provider-elasticsearch/blob/master/src/utils/elasticConnectUtil.js#L31-L34

**Comment by zakhtar1998** [comment]
FYI commenting out the auth proprty gave the same error, as there are many references that require the username and password in the node_modules e.g. node_modules/@elastic/elasticsearch/index.js, node_modules/@koopjs/provider-elasticsearch/src/model.js. So I will give it a try by commenting out there references even though there is a tight connection between alot of files.

**Comment by dhatcher** [comment]
If you just put an empty string in the config for the userName and password it should all pass through fine. That's the way I run it on clusters that don't require authorization.

**Comment by zakhtar1998** [comment]
I did try this, but it still gave the same error.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/103567436/163466887-5237a6bf-9475-4742-957a-52f303383dce.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/103567436/163466917-46892f0c-04fd-4c55-9860-e234dea3c5b5.png">

**Comment by zakhtar1998** [comment]
I tried adding it to the config, but still, receive the same error for some reason.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/103567436/163467156-f4c6b2b6-3991-435a-85b7-0bdae81c2958.png">
<img width="958" alt="image" src="https://user-images.githubusercontent.com/103567436/163467230-7d26be4d-56c9-46db-a02f-9cb971bc7041.png">

**Comment by dhatcher** [comment]
I see a few other problems. Your URL looks incorrect, from your config it should be more like

``` /es/rest/services/local/myService1/FeatureServer```

It looks like the field you are pointing to for geometry is also an object, not a geo_point field. So that will most likely fail as well.

**Comment by dhatcher** [comment]
You should also double check your return fields, if they are nested you need to include the full path to them, so for instance _location_info.resolved_location.lat_ instead of just _lat_

**Comment by zakhtar1998** [comment]
Oh I see, yes we were a bit unclear about the URL construction, especially with :host and :id. Thanks for clarifying this! With regards to the geometry, instead of geo_point, we were unsure what to place here.

**Comment by zakhtar1998** [comment]
In our case do we just remove the geometryType?

**Comment by dhatcher** [comment]
That depends on what type of field has your location information. If it is actually a geo_point field then it should stay, if it's geo_shape then you can put in Point/Polyline/Polgyon as the type.  It MUST be either geo_shape or geo_point though for elastic to allow geospatial queries.

**Comment by zakhtar1998** [comment]
How does a typical geo_point field look like in ES? Does it combine both the lat and lon together? This is because our index has them as separate, so would that mean we have to adjust our index?

This is because with the current config, the koop does not start on https://flood-insights.qcri.org/es/rest/services/local/myService1/FeatureServer as it provides the same error.
<img width="435" alt="image" src="https://user-images.githubusercontent.com/103567436/163499675-0c398d34-3c84-43c4-ae49-271f8c9ed8c2.png">
<img width="938" alt="image" src="https://user-images.githubusercontent.com/103567436/163499771-86ccebba-47a8-4944-bb5a-835b56192201.png">

**Comment by zakhtar1998** [comment]
I think by adding the userName and password in the config file, it does not resolve the error. Even others try adding userName and password in this Issue: https://github.com/koopjs/koop-provider-elasticsearch/issues/48# and I am not sure if they were able to do so successfully.

**Comment by zakhtar1998** [comment]
Good new, looks like I have got it to work, I edited the config file to look like this:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/103567436/163628761-03cb1bdb-4cce-4143-9e76-6ec8f77cadce.png">

And when i access https://flood-insights.qcri.org/es/rest/services/local/myService1/FeatureServer i see the following:
<img width="1596" alt="image" src="https://user-images.githubusercontent.com/103567436/163628673-5dd0dc0b-fc0f-4913-ae8d-acf8b41d8f9d.png">

And these are the warnings i see:
<img width="970" alt="image" src="https://user-images.githubusercontent.com/103567436/163628637-653b5da6-fe04-4a8e-84a9-94109c7b8e3b.png">

Are these warning something that will cause issues later on?

**Comment by zakhtar1998** [comment]
This is the mapping for the resolve_location:

                        "resolved_location": {
                            "properties": {
                                "address": {
                                    "properties": {
                                        "city": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "type": "keyword"
                                                }
                                            }
                                        },
                                        "country": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "type": "keyword",
                                                    "ignore_above": 256
                                                }
                                            }
                                        },
                                        "country_code": {
                                            "type": "keyword"
                                        },
                                        "county": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "type": "keyword",
                                                    "ignore_above": 256
                                                }
                                            }
                                        },
                                        "neighbourhood": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "type": "keyword",
                                                    "ignore_above": 256
                                                }
                                            }
                                        },
                                        "state": {
                                            "type": "text",
                                            "fields": {
                                                "keyword": {
                                                    "type": "keyword"
                                                }
                                            }
                                        }
                                    }
                                },
                                "geohash": {
                                    "type": "geo_point"
                                },
                                "lat": {
                                    "type": "double"
                                },
                                "lon": {
                                    "type": "double"
                                },
                                "query_term": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "type": "keyword"
                                        }
                                    }
                                },
                                "response": {
                                    "type": "text",
                                    "index": false
                                }
                            }
                        },


As you can see that it is geo_point.
