### ISSUE TITLE
Time filter not working

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop-provider-elasticsearch#5]
It appears that other filters are working in agol / portal for arcgis.  however when I try to use the time filter it no longer works, thowing 

**(node:7314) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 41): SyntaxError: Syntax error found near Identifier (WHERE Clause**)

This is the qs param that I am passing

query?f=json&where=timestamp%20BETWEEN%20timestamp%20%272018-04-08%2005%3A00%3A00%27%20AND%20timestamp%20%272018-04-09%2004%3A59%3A59%27&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=%7B"xmin"%3A-10801469.341038998%2C"ymin"%3A3443946.7464246675%2C"xmax"%3A-10644926.307111034%2C"ymax"%3A3600489.7803526316%2C"spatialReference"%3A%7B"wkid"%3A102100%2C"latestWkid"%3A3857%7D%7D&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&outSR=102100&callback=dojo_request_script_callbacks.dojo_request_script38

**Comment by dhatcher** [comment]
Not that much time though.  It should be fixed now if you get latest.

**Comment by keithfraley** [comment]
this appears to be fixed!
