### ISSUE TITLE
Aggregations

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop-provider-elasticsearch#7]
I love this project, I am curious if you have started to think about leveraging aggregations in es much the way BDS does?  We have done some work on this and might be able to help along this journey.

**Comment by keithfraley** [comment]
Is that separate from bds?

**Comment by dhatcher** [comment]
Yes it is.  It also aggregates along the entire geometry of a polyline/polygon.  So if a shape crosses aggregation boundaries it gets counted in all of them that include any/all of its geometry.

**Comment by dhatcher** [comment]
@keithfraley If you need more information about this you can email me.  dhatcher at esri dot com.
