### ISSUE TITLE
Filter not working with string values with spaces

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop-provider-elasticsearch#8]
f=json&where=navstat%20%3D%20%27under%20way%20using%20engine%27&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=%7B"xmin"%3A-15028131.257092927%2C"ymin"%3A5009377.085700966%2C"xmax"%3A-10018754.171396947%2C"ymax"%3A10018754.171396947%2C"spatialReference"%3A%7B"wkid"%3A102100%2C"latestWkid"%3A3857%7D%7D&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&outSR=102100&callback=dojo_request_script_callbacks.dojo_request_script2413

It appears the filter is not working with string values that multiple words or spaces

**Comment by keithfraley** [comment]
I thinking this may be an issue with winnow?

**Comment by dhatcher** [comment]
There were a couple of things keeping this from working correctly.  I think they should be sorted out in the latest update.

**Comment by keithfraley** [comment]
I have updated and am still seeing the same issues.
name is 'JWA SANTOS' **returns nothing**
typedescription is 'boat' **returns correctly**
typedescription is 'Military Operations' **returns nothing**


I am still, however, not seeing anything loading into the table whether the filter comes back correctly or not.

**Comment by dhatcher** [comment]
Ahh, I thought you were using contains.  I'll check that.

**Comment by dhatcher** [comment]
So this is happening because your text field is analyzed.  If you used an un-analyzed textfield or the .keyword off of the field it would work.

I could change the provider to do a phrase match on an 'is' query but then you would get results that look pretty much like a 'contains' query.

**Comment by keithfraley** [comment]
any high level advice on how to model fields in es for optimized use with koop?

**Comment by dhatcher** [comment]
If you're using a newer version of ES your fields should have a keyword property by default.  I just pushed a change that will let you use FIELD_NAME.keyword as a field in your configuration file.  Then = will work as expected. 

If your fields don't have the built in keyword property you can still use contains.  This will give extra results though in some cases.

For instance, if you search for a value of 'the dog' and a document has a value 'the dog is blue' it will match.

**Comment by keithfraley** [comment]
seems to be working now!

Thanks.  Still no data is loading into table
