### ISSUE TITLE
polygon service has point renderer

### ISSUE THREAD

**Issue by AndrewGriffinGIT** [koopjs/koop-provider-elasticsearch#85]
Not sure why I cant get polygons to render. In es how should i set the mapping, geo_shape or shape. For value to insert should it be string wkt?  

    "geometry": "POLYGON ((-95.62829707113862 29.99388366204915, -95.62853292235582 29.994088598628586, -95.62853598596803 29.994126824084642, -95.62836662022042 29.994282742975376, -95.62828537578142 29.994223282183523, -95.62810862399301 29.994053385238534, -95.62811578108486 29.9940470115642, -95.62829707113862 29.99388366204915))"
  }
}

        "geometry": {
          "type": "shape"
        },

      "indices": {
        "polyService": {
          "index": "hcad2",
          "geometryField": "geometry",
          "geometryType": "Polygon",
          "reversePolygons": false,
          "returnFields": [
            "hcad_num",
            "owner",
            "appr_val"
          ],
          "dateFields": [],
          "subLayers": [],
          "maxResults": 1000
        }
      }

**Comment by dhatcher** [comment]
There was no support for WKT geometries within the provider. This is fixed as of today in version 3.7.1
